### ISSUE TITLE
Move under reports?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/github_stats#6]
The main admin menu can get long quickly -- would it make sense to move this under Reports?

**Comment by indigoxela** [comment]
> ...would it make sense to move this under Reports?

That's actually where I wanted to put them first, but it turned out to be not ideal.
The path would have to be **admin**/something... then.

Which means, that:

1. It would make this page sort of an admin report page (path admin/... has different perms)
2. The path wouldn't match the github-project/add (and other) paths anymore

Not too bad, but a bit confusing IMO. But you can move that item there (via views or the management menu).

**Comment by laryn** [comment]
Ok.
